exports.queryList = {
  GET_STORE_LIST_QUERY:
    "SELECT STOREID, STORENAME, STORECODE, CREATEDON, CREATEDBY FROM BMS.STORE",
  // INSERT_STORE : `INSERT INTO BMS.STORE(STORENAME, STORECODE, CREATEDON, CREATEDBY) VALUES(${STORENAME} , ${STORECODE} , ${CREATEDON} , ${CREATEDBY})`
  // INSERT_STORE : 'INSERT INTO BMS.STORE(STORENAME, STORECODE, CREATEDON, CREATEDBY) VALUES("","","","")'
  INSERT_STORE:
    "INSERT INTO BMS.STORE(STORENAME, STORECODE, CREATEDON, CREATEDBY) VALUES (?1, ?2, ?3, ?4)",

  GET_BOOK_LIST_QUERY:
    "SELECT BOOKID, BOOKTITLE, BOOKDESCRIPTION, BOOKAUTHOR, BOOKPUBLISHER, BOOKPAGES, STORECODE, CREATEDON, CREATEDBY FROM BMS.BOOK",

  INSERT_BOOK:
    "INSERT INTO BMS.BOOK (BOOKTITLE, BOOKDESCRIPTION, BOOKAUTHOR, BOOKPUBLISHER, BOOKPAGES, STORECODE, CREATEDON, CREATEDBY) VALUES(?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
  GET_BOOK_DETAILES_LIST_QUERY: "SELECT * FROM bms.Book WHERE bookId = ?",

  UPDATE_BOOK:
    'UPDATE BMS.BOOK SET BOOKTITLE="", BOOKDESCRIPTION="", BOOKAUTHOR="", BOOKPUBLISHER="", BOOKPAGES=0, STORECODE="", CREATEDON="", CREATEDBY="" WHERE BOOKID=NEXTVAL("BMS.BOOK_BOOKID_SEQ"::REGCLASS)',
  DELETE_BOOK:
    'DELETE FROM BMS.BOOK WHERE BOOKID=NEXTVAL("BMS.BOOK_BOOKID_SEQ"::REGCLASS)',
};
